version: "3.9"

services:
  app:
    build:
      context: .
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - APP_PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=postgrespwd
      - DB_HOSTNAME=localhost
      - DB_PORT=5432
      - DB_DATABASE=postgres
    links:
      - db
    deploy:
      resources:
        limits:
          memory: 1G
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
